fix for ECM

diff --git a/qca-nss-clients/files/qca-nss-ovpn.init b/qca-nss-clients/files/qca-nss-ovpn.init
--- a/qca-nss-clients/files/qca-nss-ovpn.init
+++ b/qca-nss-clients/files/qca-nss-ovpn.init
@@ -18,87 +18,87 @@
 USE_PROCD=1
 
 ecm_disable() {
-  if [ ! -d /sys/module/ecm ]; then
-    return
-  fi
+	if [ ! -d /sys/module/ecm ]; then
+		return
+	fi
 
-  echo 1 > /sys/kernel/debug/ecm/front_end_ipv4_stop
-  echo 1 > /sys/kernel/debug/ecm/front_end_ipv6_stop
-  echo 1 > /sys/kernel/debug/ecm/ecm_db/defunct_all
+	echo 1 > /sys/kernel/debug/ecm/front_end_ipv4_stop
+	echo 1 > /sys/kernel/debug/ecm/front_end_ipv6_stop
+	echo 1 > /sys/kernel/debug/ecm/ecm_db/defunct_all
 }
 
 ecm_enable() {
-  if [ ! -d /sys/module/ecm ]; then
-    return
-  fi
+	if [ ! -d /sys/module/ecm ]; then
+		return
+	fi
 
-  echo 0 > /sys/kernel/debug/ecm/ecm_db/defunct_all
-  echo 0 > /sys/kernel/debug/ecm/front_end_ipv4_stop
-  echo 0 > /sys/kernel/debug/ecm/front_end_ipv6_stop
+	echo 0 > /sys/kernel/debug/ecm/ecm_db/defunct_all
+	echo 0 > /sys/kernel/debug/ecm/front_end_ipv4_stop
+	echo 0 > /sys/kernel/debug/ecm/front_end_ipv6_stop
 }
 
 check_enabled() {
-  local enabled
-  total_enabled=${total_enabled:-0}
-  config_get_bool enabled "$1" enabled 0
-  [ "$enabled" = "1" ] && total_enabled=$((total_enabled + 1))
+	local enabled
+	total_enabled=${total_enabled:-0}
+	config_get_bool enabled "$1" enabled 0
+	[ "$enabled" = "1" ] && total_enabled=$((total_enabled + 1))
 }
 
 mod_action() {
-  local action="$1"
+	local action="$1"
 
-  if [ "$action" != "load" -a "$action" != "unload" ]; then
-    echo "Invalid action: $action, must be load or unload"
-    return
-  fi
+	if [ "$action" != "load" -a "$action" != "unload" ]; then
+		echo "Invalid action: $action, must be load or unload"
+		return
+	fi
 
-  shift
-  local modules="$*"
+	shift
+	local modules="$*"
 
-  [ -z "$modules" ] && {
-    echo "No modules specified"
-    return
-  }
+	[ -z "$modules" ] && {
+		echo "No modules specified"
+		return
+	}
 
-  for i in $modules; do
-    [ -n "$i" ] && {
-      if [ "$action" = "unload" ]; then
-        grep -q -w "$i" /proc/modules && {
-          rmmod "$i" || echo "Failed to unload $i"
-        }
-      else
-        modprobe "$i" 2> /dev/null || {
-          echo "Failed to load $i"
-          return
-        }
-      fi
-    }
-  done
+	for i in $modules; do
+		[ -n "$i" ] && {
+			if [ "$action" = "unload" ]; then
+				grep -q -w "$i" /proc/modules && {
+					rmmod "$i" || echo "Failed to unload $i"
+				}
+			else
+				modprobe "$i" 2> /dev/null || {
+					echo "Failed to load $i"
+					return
+				}
+			fi
+		}
+	done
 }
 
 start_service() {
-  config_load openvpn
-  config_foreach check_enabled openvpn
+	config_load openvpn
+	config_foreach check_enabled openvpn
 
-  [ "$total_enabled" = "0" ] && return
+	[ "$total_enabled" = "0" ] && return
 
-  ecm_disable
+	ecm_disable
 
-  /etc/init.d/openvpn stop 2> /dev/null
+	/etc/init.d/openvpn stop 2> /dev/null
 
-  mod_action unload qca_nss_ovpn_link qca_nss_ovpn_mgr
-  mod_action load qca_nss_ovpn_link qca_nss_ovpn_mgr ovpn_dco_v2
+	mod_action unload qca_nss_ovpn_link qca_nss_ovpn_mgr
+	mod_action load qca_nss_ovpn_link qca_nss_ovpn_mgr ovpn_dco_v2
 
-  ecm_enable
+	ecm_enable
 
-  /etc/init.d/openvpn start 2> /dev/null
+	/etc/init.d/openvpn start 2> /dev/null
 }
 
 stop_service() {
-  ecm_disable
+	ecm_disable
 
-  /etc/init.d/openvpn stop 2> /dev/null
-  mod_action unload qca_nss_ovpn_link qca_nss_ovpn_mgr
+	/etc/init.d/openvpn stop 2> /dev/null
+	mod_action unload qca_nss_ovpn_link qca_nss_ovpn_mgr
 
-  ecm_enable
+	ecm_enable
 }
